### ISSUE TITLE
پیشنهادات برای پروژه تون

### ISSUE THREAD

**Issue by hadi-shakibazad** [POYANr11/FerdosiLibrary#1]
سلام امیدوارم حالتون خوب باشه

پروژه تون برام جالب بود و یه سری نکانی رو دیدم که بهتر بود بهش اضاف کنید

شما `SECRET_KEY` رو هم توی گیت هاب گذاشته بودید که کار خیلی خطرناکیه. اگر این پروژه رو دیپلوی کردید و این رو تغییر ندادید سایتتون میتونه به راحتی هک بشه
برای اینکه لازم نباشه مستقیم تو گیت هاب `SECRET_KEY` رو قرار بدید میتونید از متغیرهای محیطی استفاده کنید

از فایل `gitignore.` استفاده کنید تا چیزایی مثل فایل دیتابیس توی گیت هاب کامیت نشه

فایل `requirements.txt` رو اضافه کنید تا کتابخونه های مورد نیاز برای اجرای پروژتون معلوم باشه

چیزای دیگه هم هست که پروژه رو میتونه خیلی حرفه ای تر بکنه مثل `CI/CD` و فایل `README.md` و تست نوشتن برای پروژتون

**Comment by POYANr11** [comment]
سلام
مرسی از نظر لطفت❤️
این پروژه رو سر یه قضیه ای پابلیکش کردم ولی یادم رفت دوباره پرایویتش کنم😂💔
بله اطلاع دارم متاسفانه چه کار خطرناکی کردم
ولی احتمالا بعدا پابلیکش کنم و در اون صورت قطعا این نکات رو رعایت می‌کنم
ولی بازم خیلی ممنون🙏

**Comment by hadi-shakibazad** [comment]
عزیزمی ❤️
